### ISSUE TITLE
No licence information

### ISSUE THREAD

**Issue by IxelBox** [thelarz/MvcBreadCrumbs#1]
this is a great libary, thanks for publishing!
But there was no license specified so I can't use it or expanding the libary.

**Comment by thelarz** [comment]
Thanks!  I'll get a license on it for you. I don't understand all the different types but this library will be free to use with no conditions.

**Comment by IxelBox** [comment]
My rules to select a license are the follow.
If I do not care then I take the [WTFPL](http://www.wtfpl.net/).
If the source code may be free (open) should remain, but used in commercial applications, the [Apache license](http://www.apache.org/licenses/LICENSE-2.0) is good.
Otherwise, use the [GPL](http://www.gnu.org/licenses/gpl-3.0.en.html), every code must be open after use.

**Comment by thelarz** [comment]
Ok, that's done GPL license. I hope you enjoy the lib.  Let me know if you
have suggestions. It's very new and probably needs many updates.

Larry

**Comment by IxelBox** [comment]
I can't use it for work, because my customer don't accept GPL code.

**Comment by thelarz** [comment]
Oh well.  That's weird. But ok.
