### ISSUE TITLE
Localized?

### ISSUE THREAD

**Issue by Milad-Darvishi** [thelarz/MvcBreadCrumbs#9]
How To use Localized This BreadCrumb?

**Comment by thelarz** [comment]
I'm not sure what you need. If you want to issue a pull-request with your changes, I'll consider merging it in.  Thanks!

**Comment by vavanv** [comment]
Is there way to use Localized  Resource for label?

**Comment by thelarz** [comment]
We could potentially implement something like this http://stackoverflow.com/a/359360/3435313

**Comment by Milad-Darvishi** [comment]
Yes Of course.

**Comment by vavanv** [comment]
The example used DisplayNameAttribute but we are using ActionFilterAttribute
I think, we need another Attribute - like BreanCrumbLabelAttribute and in use it in BreadCrumbAttribute
like http://stackoverflow.com/questions/19412483/mvc3-can-you-give-controller-a-display-name

**Comment by thelarz** [comment]
Yes, of course. I was just showing that as an example.

**Comment by vavanv** [comment]
I am going to try in local dev env and if it works will ask to merge the solution

**Comment by vavanv** [comment]
it works fine by adding BreanCrumbLabelAttribute  : DisplayNameAttribute  and use it in BreadCrumbAttribute.
Needs more dev to finalize it

**Comment by vavanv** [comment]
I am implemented it using existing DisplayAttribute, not sure how to proceed with pushing (never done it before)... could smbd explain? Thanks

**Comment by thelarz** [comment]
As long as you "forked" to your own repo correctly, you should be able to commit/push your changes to remote and then go to github and create a pull request.  

https://help.github.com/articles/using-pull-requests/

**Comment by vavanv** [comment]
I forked, made changes, and created a pull request

**Comment by thelarz** [comment]
I've deployed the localization change pull-request. Closing the issue.  Thanks folks!
